language: node_js
node_js: lts/*
jobs:
  include:
    - stage: DEPLOY
      script: './build.sh'
      deploy:
        app: lets-write-it-out
        api_key:
          secure: kUexLrtRwZQx3rTYwv+YP59zjcO6/to0KAhEBou0MdesqG76XZkecYobCS2KYTavA7aAcZ0NA7ZNaYQa4zqSirhX1HgW/PXb6TdtB7QpDQKf6xQExXW6jDE05e9A8R7uwq1ENm9LJICrQjy9ksAufm84NuB1s18rcFx9X7z5rS7y9KFvcsitvKkEPEXRepAtSei0DeBvetyDy5/CNVl/M3u+yIPagypd9jiFlhgCw5BYtchlNSksESAhw+5VFWIVnP6EfPrHXNmm+dP+TMyYGuoIeXFF8NWpw0Vp0mMGOCTvYIaEM6CzlbXv4bhswG2NjdbVfX3Yy9fvRr5Od+WjZs4rnsfR2WolkmQsB2mAb7ln0PyPzu3iNOwY6ZGESDWIY0mOa5Fx46FR0xIt6ewdSI8Sw4P+f6rfy88CDoMaIPA+5ySxWqX+56PjMcNdfaKEjAEcuhX85v/U3XNimtbStT8TqVId1pe/b5N0/ZdmJ8e8nGQRoeNtYYl8e1Oi1ptNHPUfNuDs4EUY51YmRT+rP/jnQfT7rOhefktbBrfBrEgBAttY6/+ultfkN9OoxqyzCsg1r9LKZ9mJHZiIbwso2tsMS8Axmdf0pBjqT9MhAOwAwb7zt9C68iJpZ5Amvamua2keDz7iv/lfOgEjZ7JVx0sIJfBdoXWU50h8maBMgVA=
        provider: heroku
        run: restart
        skip_cleanup: true
